### PR TITLE
Setup travis

### PR DESCRIPTION
**Pull request by BDHernand**
Travis files for the swift-buildpack.

### CODE REVIEW

**Comment by rolivieri** [comment]
- [ ]  Research specifying ruby version inside travis.yml file. As a reference, see https://docs.travis-ci.com/user/languages/ruby/.

**Comment by rolivieri** [comment]
- [ ] Rename DELETE to DELETE_FLAG
- [ ] Rename push_and_optionally_delete to push_application
- [ ] Rename KITURA_STARTER_TIME to KITURA_STARTER_PUSH_TIME 
- [ ] Rename SWIFT_HELLOWORLD_TIME to SWIFT_HELLOWORLD_PUSH_TIME

**Comment by BDHernand** [comment]
@rolivieri all changes have been made.  Doing final tests now

**Comment by BDHernand** [comment]
@rolivieri changes were made to the readme and the travis file for the branches and deploy sections

**Pull request merged**
