### PR TITLE
Support Swift 5.1

### PR DESCRIPTION
**Pull request by gee4vee**

### CODE REVIEW

**Review by christiancompton — COMMENTED** [review]
We should be using 5.0.3 here, not 5.0.2

**Review by christiancompton — COMMENTED** [review]
Let's remove 4.2.4 out of the manifest also

**Comment by gee4vee** [comment]
> Let's remove 4.2.4 out of the manifest also

Done.

**Comment by gee4vee** [comment]
> We should be using 5.0.3 here, not 5.0.2

Done.

**Pull request merged**
